---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-armv7
  environment:
    PKG_SIGN_KEY:
      from_secret: pkg_sign_key
  commands:
  - build.sh

- name: upload
  image: plugins/s3
  settings:
    region: ap-southeast-2
    bucket: apks-phoenixphire
    acl: private
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: /home/buildozer/packages/*
    target: /packages

trigger:
  event:
    - pull_request
---
kind: pipeline
name: edge-aarch64

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-aarch64
  environment:
    PKG_SIGN_KEY:
      from_secret: pkg_sign_key
  commands:
  - build.sh

- name: upload
  image: plugins/s3
  settings:
    region: ap-southeast-2
    bucket: apks-phoenixphire
    acl: private
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: /home/buildozer/packages/*
    target: /packages

trigger:
  event:
    - pull_request
...
