---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-armv7
  commands:
  - build.sh
  environment:
    PKG_SIGN_KEY:
      from_secret: PKG_SIGN_KEY
    PKG_SIGN_PUB:
      from_secret: PKG_SIGN_PUB
    TEST_TEST_VAR:
      from_secret: test_var

trigger:
  event:
    - pull_request
---
kind: pipeline
name: edge-aarch64

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-aarch64
  commands:
  - build.sh
  environment:
    PKG_SIGN_KEY:
      from_secret: PKG_SIGN_KEY
    PKG_SIGN_PUB:
      from_secret: PKG_SIGN_PUB
    TEST_TEST_VAR:
      from_secret: test_var

trigger:
  event:
    - pull_request
...
