---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-armv7
  failure: ignore
  commands:
    - build.sh

- name: diskcheck
  image: phoenixmage/alpine-drone-ci:edge-armv7
  commands:
    - df -h


trigger:
  event:
    - pull_request
...
