---
kind: pipeline
name: v3.11-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

workspace:
  base: /home/buildozer

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:v3.12-armv7
  environment:
    PKG_SIGN_KEY:
      from_secret: pkg_sign_key
  commands:
  - build.sh

- name: upload
  image: appleboy/drone-scp
  settings:
    host: phoenixphire.no-ip.org
    target: ~/
    source: packages/*
    username:
      from_secret: ssh-username
    password:
      from_secret: ssh-password

trigger:
  event:
    - pull_request
---
kind: pipeline
name: v3.11-aarch64

platform:
  os: linux
  arch: arm64

clone:
  disable: true

workspace:
  base: /home/buildozer

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:v3.12-aarch64
  environment:
    PKG_SIGN_KEY:
      from_secret: pkg_sign_key
  commands:
  - build.sh

- name: upload
  image: appleboy/drone-scp
  settings:
    host: phoenixphire.no-ip.org
    target: ~/
    source: packages/*
    username:
      from_secret: ssh-username
    password:
      from_secret: ssh-password

trigger:
  event:
    - pull_request
...
