---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

workspace:
  base: /home/buildozer

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-armv7
  environment:
    PKG_SIGN_KEY:
      from_secret: pkg_sign_key
  commands:
  - build.sh

- name: upload
  image: appleboy/drone-scp
  settings:
    host: phoenixphire.no-ip.org
    target: packages
    source: packages/*
    username:
      from-secret: ssh-username
    password:
      from-secret: ssh-password

trigger:
  event:
    - pull_request
---
kind: pipeline
name: edge-aarch64

platform:
  os: linux
  arch: arm64

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:edge-aarch64
  environment:
    PKG_SIGN_KEY:
      from_secret: pkg_sign_key
  commands:
  - build.sh

trigger:
  event:
    - pull_request
...
