---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenix/alpine-drone-ci:edge-armv7
  commands:
  - build.sh

...
