---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  failure: ignore
  image: phoenixmage/alpine-drone-ci:edge-armv7
  commands:
    - awk -F\: '/^[0-9]+:memory:/ { filepath="/sys/fs/cgroup/memory"$3"/memory.limit_in_bytes"; getline line < filepath; print line }' /proc/self/cgroup
    - build.sh
    - df -h

trigger:
  event:
    - pull_request
...
