---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: phoenixmage/alpine-drone-ci:v3.9-armv7
  commands:
  - build.sh

trigger:
  event:
    - pull_request

...
