---
kind: pipeline
name: edge-armv7

platform:
  os: linux
  arch: arm

clone:
  disable: true

steps:
- name: build
  pull: always
  image: docker pull phoenixmage/alpine-drone-ci:latest
  commands:
  - build.sh

...
